language: cpp
compiler: gcc
dist: trusty

before_install:
  # C++14
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install: 
  # C++14
  - sudo apt-get install -qq g++-6
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
  # scan-build
  - sudo apt-get install -qq clang

script: 
  - clang -v
  # Build and run this project
  - scan-build qmake
  - scan-build make debug
  - scan-build ./travis_qmake_gcc_cpp14_scan-build
